[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
solc = '0.8.17'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

fs_permissions = [{ access = "write", path = "./"}]
